import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { RiskLevel } from "../security/policy.js";
import { dryRun, registerTool, type ToolContext } from "./context.js";
import { dryRunField } from "./schemas.js";

const username = z.string().min(1).max(128);
const roleId = z.string().min(1).max(128);
const call = (ctx: ToolContext, method: string, parameters: Record<string, unknown> = {}, idempotent = false) => ctx.provider.callApi("Core", method, parameters, { idempotent });

export function registerAdminTools(server: McpServer, ctx: ToolContext): void {
  registerTool(server, ctx, "amp_list_users", { title: "List AMP users", description: "List AMP user summaries without credentials or password hashes.", risk: RiskLevel.READ_ONLY, schema: {} }, () => call(ctx, "GetAMPUsersSummary", {}, true));
  registerTool(server, ctx, "amp_get_user", { title: "Get AMP user", description: "Get one AMP user's non-secret profile.", risk: RiskLevel.READ_ONLY, schema: { username } }, ({ username }) => call(ctx, "GetAMPUserInfo", { Username: username }, true));
  registerTool(server, ctx, "amp_create_user", { title: "Create AMP user", description: "Create a user and optionally assign an initial password. Passwords are redacted from all audit logs.", risk: RiskLevel.LOW_RISK_WRITE, schema: { username, initialPassword: z.string().min(8).max(1024).optional(), ...dryRunField } }, async (args) => dryRun(args, { username: args.username, initialPassword: args.initialPassword ? "[REDACTED]" : undefined, apiActions: ["Core/CreateUser", ...(args.initialPassword ? ["Core/ResetUserPassword"] : [])] }, async () => {
    const created = await call(ctx, "CreateUser", { Username: args.username }); const passwordResult = args.initialPassword ? await call(ctx, "ResetUserPassword", { Username: args.username, NewPassword: args.initialPassword }) : undefined; return { created, passwordSet: Boolean(args.initialPassword), passwordResult };
  }));
  registerTool(server, ctx, "amp_update_user", { title: "Update AMP user", description: "Update AMP user account flags and optional email address.", risk: RiskLevel.LOW_RISK_WRITE, schema: { username, disabled: z.boolean(), passwordExpires: z.boolean(), cannotChangePassword: z.boolean(), mustChangePassword: z.boolean(), emailAddress: z.email().or(z.literal("")).optional(), ...dryRunField } }, (args) => dryRun(args, { username: args.username, apiAction: "Core/UpdateUserInfo" }, () => call(ctx, "UpdateUserInfo", { Username: args.username, Disabled: args.disabled, PasswordExpires: args.passwordExpires, CannotChangePassword: args.cannotChangePassword, MustChangePassword: args.mustChangePassword, ...(args.emailAddress !== undefined ? { EmailAddress: args.emailAddress } : {}) })));
  const userDanger = (name: string, method: string, withPassword = false) => registerTool(server, ctx, name, { title: name.replaceAll("_", " "), description: withPassword ? "Administratively reset a user's password. The value is never logged." : "Delete an AMP user account. This does not expose or return credentials.", risk: RiskLevel.DESTRUCTIVE, schema: { username, ...(withPassword ? { newPassword: z.string().min(8).max(1024) } : {}), ...dryRunField } }, (args: any) => dryRun(args, { username: args.username, apiAction: `Core/${method}` }, () => call(ctx, method, { Username: args.username, ...(withPassword ? { NewPassword: args.newPassword } : {}) })));
  userDanger("amp_delete_user", "DeleteUser"); userDanger("amp_reset_user_password", "ResetUserPassword", true);

  registerTool(server, ctx, "amp_list_roles", { title: "List AMP roles", description: "List AMP authorization roles.", risk: RiskLevel.READ_ONLY, schema: {} }, () => call(ctx, "GetRoleData", {}, true));
  registerTool(server, ctx, "amp_get_role", { title: "Get AMP role", description: "Get an AMP role summary by ID.", risk: RiskLevel.READ_ONLY, schema: { roleId } }, ({ roleId }) => call(ctx, "GetRole", { RoleId: roleId }, true));
  registerTool(server, ctx, "amp_create_role", { title: "Create AMP role", description: "Create an AMP authorization role.", risk: RiskLevel.LOW_RISK_WRITE, schema: { name: z.string().min(1).max(128), commonRole: z.boolean().default(false), ...dryRunField } }, (args) => dryRun(args, { roleName: args.name, apiAction: "Core/CreateRole" }, () => call(ctx, "CreateRole", { Name: args.name, AsCommonRole: args.commonRole })));
  registerTool(server, ctx, "amp_update_role", { title: "Rename AMP role", description: "Update the name of an existing AMP authorization role.", risk: RiskLevel.LOW_RISK_WRITE, schema: { roleId, newName: z.string().min(1).max(128), ...dryRunField } }, (args) => dryRun(args, { roleId: args.roleId, newName: args.newName, apiAction: "Core/RenameRole" }, () => call(ctx, "RenameRole", { RoleId: args.roleId, NewName: args.newName })));
  registerTool(server, ctx, "amp_delete_role", { title: "Delete AMP role", description: "Delete an authorization role; assigned users can lose access.", risk: RiskLevel.DESTRUCTIVE, schema: { roleId, ...dryRunField } }, (args) => dryRun(args, { roleId: args.roleId, apiAction: "Core/DeleteRole" }, () => call(ctx, "DeleteRole", { RoleId: args.roleId })));
  registerTool(server, ctx, "amp_get_permissions", { title: "Get AMP permission metadata", description: "Return the permission specification and, if roleId is supplied, the role's enabled permissions.", risk: RiskLevel.READ_ONLY, schema: { roleId: roleId.optional() } }, async ({ roleId }) => ({ specification: await call(ctx, "GetPermissionsSpec", {}, true), ...(roleId ? { rolePermissions: await call(ctx, "GetAMPRolePermissions", { RoleId: roleId }, true) } : {}) }));
  registerTool(server, ctx, "amp_set_permissions", { title: "Set AMP role permission", description: "Enable, disable, or inherit one exact AMP permission node for a role.", risk: RiskLevel.DESTRUCTIVE, schema: { roleId, permissionNode: z.string().min(1).max(256), enabled: z.boolean().nullable().describe("null restores inherited/default behavior"), ...dryRunField } }, (args) => dryRun(args, { roleId: args.roleId, permissionNode: args.permissionNode, enabled: args.enabled, apiAction: "Core/SetAMPRolePermission" }, () => call(ctx, "SetAMPRolePermission", { RoleId: args.roleId, PermissionNode: args.permissionNode, Enabled: args.enabled })));
}
