import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { RiskLevel } from "../security/policy.js";
import { dryRun, registerTool, type ToolContext } from "./context.js";
import { dryRunField, instanceId } from "./schemas.js";

export function registerBackupTools(server: McpServer, ctx: ToolContext): void {
  const call = (instanceId: string, method: string, parameters: Record<string, unknown> = {}, idempotent = false) => ctx.provider.callApi("LocalFileBackupPlugin", method, parameters, { instanceId, idempotent });
  registerTool(server, ctx, "amp_list_backups", { title: "List AMP backups", description: "Return the instance's backup records, including IDs and metadata supplied by AMP.", risk: RiskLevel.READ_ONLY, schema: { instanceId } }, ({ instanceId }) => call(instanceId, "GetBackups", {}, true));
  registerTool(server, ctx, "amp_create_backup", { title: "Create AMP backup", description: "Start a local instance backup with title, description and optional pin/sticky state.", risk: RiskLevel.LOW_RISK_WRITE, schema: { instanceId, title: z.string().min(1).max(200), description: z.string().max(1000).default(""), pinned: z.boolean().default(false), ...dryRunField } }, (args) => dryRun(args, { target: args.instanceId, title: args.title, apiAction: "LocalFileBackupPlugin/TakeBackup" }, () => call(args.instanceId, "TakeBackup", { Title: args.title, Description: args.description, Sticky: args.pinned })));
  registerTool(server, ctx, "amp_restore_backup", { title: "Restore AMP backup", description: "Restore a backup. This can replace current application data and normally requires downtime.", risk: RiskLevel.DESTRUCTIVE, schema: { instanceId, backupId: z.string().min(1).max(128), deleteExistingData: z.boolean().default(false), ...dryRunField } }, (args) => dryRun(args, { target: args.instanceId, backupId: args.backupId, deleteExistingData: args.deleteExistingData, apiAction: "LocalFileBackupPlugin/RestoreBackup" }, () => call(args.instanceId, "RestoreBackup", { BackupId: args.backupId, DeleteExistingData: args.deleteExistingData })));
  registerTool(server, ctx, "amp_delete_backup", { title: "Delete AMP backup", description: "Permanently delete a local backup by stable backup ID.", risk: RiskLevel.DESTRUCTIVE, schema: { instanceId, backupId: z.string().min(1).max(128), ...dryRunField } }, (args) => dryRun(args, { target: args.instanceId, backupId: args.backupId, apiAction: "LocalFileBackupPlugin/DeleteLocalBackup" }, () => call(args.instanceId, "DeleteLocalBackup", { BackupId: args.backupId })));
  const pin = (name: string, pinned: boolean) => registerTool(server, ctx, name, { title: `${pinned ? "Pin" : "Unpin"} AMP backup`, description: "Change AMP backup sticky/pinned retention state.", risk: RiskLevel.LOW_RISK_WRITE, schema: { instanceId, backupId: z.string().min(1).max(128), ...dryRunField } }, (args) => dryRun(args, { target: args.instanceId, backupId: args.backupId, pinned, apiAction: "LocalFileBackupPlugin/SetBackupSticky" }, () => call(args.instanceId, "SetBackupSticky", { BackupId: args.backupId, Sticky: pinned })));
  pin("amp_pin_backup", true); pin("amp_unpin_backup", false);
}
