import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { RiskLevel } from "../security/policy.js";
import { dryRun, registerTool, type ToolContext } from "./context.js";
import { dryRunField } from "./schemas.js";

const instanceName = z.string().min(1).max(64);
export function registerCliTools(server: McpServer, ctx: ToolContext): void {
  const cli = (name: string, operation: Parameters<ToolContext["cli"]["execute"]>[0], risk: RiskLevel, needsName: boolean) => registerTool(server, ctx, name, { title: name.replaceAll("_", " "), description: "Execute one fixed ampinstmgr operation locally using an argument array (never a shell). Requires AMP_ENABLE_CLI=true and is only useful when this MCP server runs on the AMP host as the correct OS user.", risk, schema: { ...(needsName ? { instanceName } : {}), ...dryRunField } }, (args: any) => { const input = { ...(args.instanceName ? { instanceName: args.instanceName } : {}) }; const built = ctx.cli.buildArgs(operation, input); return dryRun(args, { command: ctx.config.ampinstmgrPath, arguments: built }, () => ctx.cli.execute(operation, input)); });
  cli("amp_cli_info", "version", RiskLevel.READ_ONLY, false); cli("amp_cli_list_instances", "list", RiskLevel.READ_ONLY, false);
  cli("amp_cli_instance_info", "info", RiskLevel.READ_ONLY, true); cli("amp_cli_last_log", "lastLog", RiskLevel.READ_ONLY, true);
  cli("amp_cli_start", "start", RiskLevel.HOST_PRIVILEGED, true); cli("amp_cli_stop", "stop", RiskLevel.HOST_PRIVILEGED, true);
  cli("amp_cli_restart", "restart", RiskLevel.HOST_PRIVILEGED, true); cli("amp_cli_upgrade", "upgrade", RiskLevel.HOST_PRIVILEGED, true);
  registerTool(server, ctx, "amp_cli_show_ports", { title: "Show ampinstmgr ports", description: "Show host port usage for all instances or one named instance. Fixed local command; no shell.", risk: RiskLevel.READ_ONLY, schema: { instanceName: instanceName.optional() } }, ({ instanceName }) => ctx.cli.execute("ports", { ...(instanceName ? { instanceName } : {}) }));
  registerTool(server, ctx, "amp_cli_reconfigure", { title: "Reconfigure with ampinstmgr", description: "Apply validated +Area.Setting.Key/value arguments through local ampinstmgr. Prefer the HTTP API when available.", risk: RiskLevel.HOST_PRIVILEGED, schema: { instanceName, settings: z.record(z.string(), z.string()), ...dryRunField } }, (args) => { const input = { instanceName: args.instanceName, provisionSettings: args.settings }; const built = ctx.cli.buildArgs("reconfigure", input); return dryRun(args, { command: ctx.config.ampinstmgrPath, arguments: built }, () => ctx.cli.execute("reconfigure", input)); });
  registerTool(server, ctx, "amp_cli_rebind", { title: "Rebind with ampinstmgr", description: "Change local AMP instance HTTP binding through a fixed ampinstmgr command.", risk: RiskLevel.HOST_PRIVILEGED, schema: { instanceName, ipBinding: z.string().min(1).max(128), port: z.number().int().min(1).max(65535), ...dryRunField } }, (args) => { const input = { instanceName: args.instanceName, ipBinding: args.ipBinding, port: args.port }; const built = ctx.cli.buildArgs("rebind", input); return dryRun(args, { command: ctx.config.ampinstmgrPath, arguments: built }, () => ctx.cli.execute("rebind", input)); });
  registerTool(server, ctx, "amp_cli_delete_instance", { title: "Delete with ampinstmgr", description: "Delete a local AMP instance through a fixed ampinstmgr command. Prefer the ADS API.", risk: RiskLevel.HOST_PRIVILEGED, schema: { instanceName, skipVerification: z.boolean().default(false), ...dryRunField } }, (args) => { const input = { instanceName: args.instanceName, skipVerification: args.skipVerification }; const built = ctx.cli.buildArgs("delete", input); return dryRun(args, { command: ctx.config.ampinstmgrPath, arguments: built }, () => ctx.cli.execute("delete", input)); });
}
