import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { AmpError } from "../errors/amp-error.js";
import { RiskLevel } from "../security/policy.js";
import { dryRun, registerTool, type ToolContext } from "./context.js";
import { dryRunField, instanceId, targetId } from "./schemas.js";

const call = (ctx: ToolContext, module: string, method: string, parameters: Record<string, unknown> = {}, instance?: string, idempotent = false) => ctx.provider.callApi(module, method, parameters, { ...(instance ? { instanceId: instance } : {}), idempotent });

export function registerInstanceManagementTools(server: McpServer, ctx: ToolContext): void {
  registerTool(server, ctx, "amp_get_instance_creation_options", { title: "Discover instance creation options", description: "Dynamically retrieve supported application specs/templates, targets, datastores, provision fitness, ports and the live creation method signature.", risk: RiskLevel.READ_ONLY, schema: {} }, async () => {
    const safe = async (module: string, method: string, parameters: Record<string, unknown> = {}) => { try { return await call(ctx, module, method, parameters, undefined, true); } catch (error) { return { unavailable: error instanceof Error ? error.message : String(error) }; } };
    const [applications, targets, datastores, fitness, ports, method] = await Promise.all([safe("ADSModule", "GetSupportedApplications"), ctx.provider.listTargets(), safe("ADSModule", "GetDatastores"), safe("ADSModule", "GetProvisionFitness"), safe("Core", "GetPortSummaries"), ctx.provider.describeApiMethod("ADSModule", "CreateInstanceFromSpec").catch((error) => ({ unavailable: error instanceof Error ? error.message : String(error) }))]);
    return { applications, targets, datastores, fitness, ports, createMethod: method };
  });
  registerTool(server, ctx, "amp_get_provisioning_options", { title: "Get module provisioning options", description: "Return dynamic provisioning fields for an AMP module; use exact names and advertised values.", risk: RiskLevel.READ_ONLY, schema: { module: z.string().min(1).max(128) } }, ({ module }) => call(ctx, "ADSModule", "GetProvisionArguments", { ModuleName: module }, undefined, true));
  registerTool(server, ctx, "amp_create_instance", { title: "Create instance from AMP application spec", description: "Create a module-neutral instance using a live AMP application SpecId. Discover valid values first with amp_get_instance_creation_options.", risk: RiskLevel.DESTRUCTIVE, schema: { applicationSpecId: z.string().min(1).max(128), targetId, friendlyName: z.string().min(1).max(128), postCreate: z.number().int().min(0).max(5).default(0), startOnBoot: z.boolean().default(false), targetDatastore: z.number().int().optional(), group: z.string().max(128).optional(), ...dryRunField } }, async (args) => {
    if (!(await ctx.provider.listTargets()).some((t) => t.id.toLowerCase() === args.targetId.toLowerCase())) throw new AmpError("AMP_INVALID_PARAMETERS", `Unknown ADS target: ${args.targetId}`);
    const params = { SpecId: args.applicationSpecId, TargetADSInstance: args.targetId, FriendlyName: args.friendlyName, PostCreate: args.postCreate, StartOnBoot: args.startOnBoot, ...(args.targetDatastore !== undefined ? { TargetDatastore: args.targetDatastore } : {}), ...(args.group ? { Group: args.group } : {}) };
    return dryRun(args, { target: args.targetId, operation: "create-instance", parameters: params, apiAction: "ADSModule/CreateInstanceFromSpec" }, () => call(ctx, "ADSModule", "CreateInstanceFromSpec", params));
  });
  registerTool(server, ctx, "amp_delete_instance", { title: "Delete AMP instance", description: "Delete an AMP instance after resolving the stable ID to AMP's instance name. Backups may also become inaccessible.", risk: RiskLevel.DESTRUCTIVE, schema: { instanceId, ...dryRunField } }, async (args) => { const instance = await ctx.provider.getInstance(args.instanceId); return dryRun(args, { target: instance, apiAction: "ADSModule/DeleteInstance" }, () => call(ctx, "ADSModule", "DeleteInstance", { InstanceName: instance.name })); });
  registerTool(server, ctx, "amp_reconfigure_instance", { title: "Apply instance configuration", description: "Apply exact AMP provisioning/configuration node values. Optionally rebuild the generated configuration.", risk: RiskLevel.HOST_PRIVILEGED, schema: { instanceId, settings: z.record(z.string().min(1).max(256), z.string().max(4096)), rebuildConfiguration: z.boolean().default(false), ...dryRunField } }, (args) => dryRun(args, { target: args.instanceId, settings: args.settings, rebuildConfiguration: args.rebuildConfiguration, apiAction: "ADSModule/ApplyInstanceConfiguration" }, () => call(ctx, "ADSModule", "ApplyInstanceConfiguration", { InstanceID: args.instanceId, Args: args.settings, RebuildConfiguration: args.rebuildConfiguration })));
  registerTool(server, ctx, "amp_rebind_instance", { title: "Rebind instance network ports", description: "Replace named port mappings and optionally application IP. AMP may need to stop the instance.", risk: RiskLevel.HOST_PRIVILEGED, schema: { instanceId, portMappings: z.record(z.string().min(1).max(128), z.number().int().min(1).max(65535)), applicationIp: z.string().max(128).optional(), mustStop: z.boolean().default(true), ...dryRunField } }, (args) => dryRun(args, { target: args.instanceId, portMappings: args.portMappings, applicationIp: args.applicationIp, mustStop: args.mustStop, apiAction: "ADSModule/SetInstanceNetworkInfo" }, () => call(ctx, "ADSModule", "SetInstanceNetworkInfo", { InstanceId: args.instanceId, PortMappings: args.portMappings, ...(args.applicationIp ? { ApplicationIP: args.applicationIp } : {}), mustStop: args.mustStop })));
  registerTool(server, ctx, "amp_upgrade_instance", { title: "Upgrade AMP instance runtime", description: "Upgrade the AMP software inside one managed instance. This is distinct from updating its hosted game/application.", risk: RiskLevel.HOST_PRIVILEGED, schema: { instanceId, ...dryRunField } }, async (args) => { const instance = await ctx.provider.getInstance(args.instanceId); return dryRun(args, { target: instance, apiAction: "ADSModule/UpgradeInstance", distinction: "AMP instance runtime, not hosted application" }, () => call(ctx, "ADSModule", "UpgradeInstance", { InstanceName: instance.name })); });
  registerTool(server, ctx, "amp_check_updates", { title: "Check AMP updates", description: "Get controller or instance update information without installing anything.", risk: RiskLevel.READ_ONLY, schema: { instanceId: instanceId.optional() } }, ({ instanceId }) => call(ctx, "Core", "GetUpdateInfo", {}, instanceId, true));
  registerTool(server, ctx, "amp_update_all_instances", { title: "Upgrade all AMP instance runtimes", description: "Upgrade AMP itself inside every instance on one target. This does not update hosted games.", risk: RiskLevel.HOST_PRIVILEGED, schema: { targetId, restartRunning: z.boolean().default(false), ...dryRunField } }, (args) => dryRun(args, { target: args.targetId, restartRunning: args.restartRunning, apiAction: "ADSModule/UpgradeAllInstances" }, () => call(ctx, "ADSModule", "UpgradeAllInstances", { TargetADSInstance: args.targetId, RestartRunning: args.restartRunning })));
  registerTool(server, ctx, "amp_update_amp", { title: "Update AMP controller", description: "Trigger Core/UpgradeAMP on the ADS/controller. This can interrupt all management access and is not a hosted game update.", risk: RiskLevel.HOST_PRIVILEGED, schema: { ...dryRunField } }, (args) => dryRun(args, { target: "controller", apiAction: "Core/UpgradeAMP", distinction: "AMP controller software" }, () => call(ctx, "Core", "UpgradeAMP")));
}
